# Async Options
title:   Async
caption: "A JavaScript meetup for _Brighton & Hove_"
url:     http://asyncjs.com
email:   hello@asyncjs.com

elsewhere:
- name: News
  link: /news/
  desc: Recent Async Announcements
- name: Contact Us
  link: mailto:hello [at] asyncjs [dot] com
  desc: Get in touch
- name: Twitter
  link: http://twitter.com/asyncjs
  desc: Twitter
- name: Subscribe
  link: /feed/index.xml
  desc: Subscribe by atom feed
#- name: Subscribe by email
#  link: /
#  desc: Subscribe to email updates
- name: Calendar
  link: http://lanyrd.com/series/asyncjs/save-to-calendar/
  desc: Subscribe to out calendar
- name: Lanyrd
  link: http://lanyrd.com/series/asyncjs/
  desc: Lanyrd
- name: Mailing List
  link: http://groups.google.com/group/asyncjs/
  desc: The Async JS IRC channel
- name: IRC
  link: http://webchat.freenode.net/?channels=asyncjs
  desc: The Async JS IRC channel

# Jekyll Options
safe:        true
auto:        true
server:      true
server_port: 4000
baseurl:     /
url:         http://localhost:4000

source:      .
destination: /tmp/asyncjs
exclude:
- README.md
future:      true
lsi:         false
pygments:    false
markdown:    kramdown
permalink:   /:title
